### ISSUE TITLE
No warning or error when package name contains underscore

### ISSUE THREAD

**Issue by david-mcgillicuddy-moixa** [meta-rust/cargo-bitbake#10]
Hi, this might be my relative inexperience with bitbake speaking but I was quite surprised when my package, `foo_bar` encountered a bunch of (nothing provides `foo_bar`) errors when using the recipe generated by this crate.

Turns out the problem was that bb doesn't allow underscores in package names and changing it to `foo-bar` fixed everything.

I feel like cargo-bitbake could at least produce a warning in this case, since the file it is producing is not a valid bitbake file.
I'm not sure I'd advocate for a hard error or an implicit transformation of the name, since it's always possible to change the generated file by hand.

**Comment by cardoe** [comment]
Agreed here. This should get fixed up.

**Comment by cardoe** [comment]
Fixed with v0.3.14
