### ISSUE TITLE
Cargo Bitbake does not create recipe

### ISSUE THREAD

**Issue by olepor** [meta-rust/cargo-bitbake#12]
This might not be an issue, however:

`cargo build` succeeds.

Cargo.toml: 

`[dependencies]
serde = { version = "1.0", features = ["derive"] } # Derive Deserialization for the config struct
serde_json = "1" # serde_json
base64 = "0.10"
reqwest = "0.9"
rsa = "0.1.3"
log = "0.4"
simple_logger = "1.3.0"
hex = "0.3.2"
openssl = { version = "0.10", features = ["vendored"] }
`

And `cargo bitbake`:

`
cargo bitbake
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: no matching version `^0.4` found for package `num-bigint` (required by `rsa`)
location searched: registry `https://github.com/rust-lang/crates.io-index`
versions found: 0.2.3, 0.2.2, 0.2.1, ...
`

`cargo 1.37.0 (9edd08916 2019-08-02)`

**Comment by cardoe** [comment]
Likely this will be fixed by #14 once it lands.

**Comment by cardoe** [comment]
please try again with 0.3.13.

**Comment by cardoe** [comment]
No feedback after a few releases. Closing as fixed.
