### ISSUE TITLE
Cargo-bitbake fails when running in a Docker container or WSL2

### ISSUE THREAD

**Issue by miloszkowal** [meta-rust/cargo-bitbake#22]
When attempting to run `cargo bitbake` inside a CI/CD pipeline, which runs in a Docker container, or locally within WSL2 (which is based on Docker), I get the following error.

```
thread 'main' panicked at 'attempted to zero-initialize type `sized_chunks::sized_chunk::Chunk<(core::package_id::PackageId, im_rc::OrdMap<core::package_id::PackageId, std::vec::Vec<core::dependency::Dependency>>)>`, which is invalid', /hom
e/<user>/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/mem/mod.rs:622:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

`cargo bitbake` runs fine in Windows locally.

**Comment by RyanMeulenkamp** [comment]
I have this same problem natively under Linux :cry:

**Comment by arrascue** [comment]
I had the same problem under Windows 10.
Here is what I did, which is based on @RyanMeulenkamp steps:

- git clone https://github.com/Urcra/cargo-bitbake.git (the above-mentioned fork)
- run "cargo build" on the project "cargo-bitbake" 
- Add "[Path_to_cargo-bitbake]/target/debug" to PATH (location of cargo-bitbake.exe)
- Open a fresh PowerShell or cmd

Now "cargo bitbake" should be available.

**Comment by miloszkowal** [comment]
Yes, big thanks to @RyanMeulenkamp for this!
Also, once the #21 fork is cloned, one can run `cargo install --path path/to/fork` to install it within the `.cargo/bin` path that cargo uses already (where the default `cargo install` command installs packages)

**Comment by jwinarske** [comment]
I see the same error with stable rust on both Mac and Linux.  https://github.com/meta-rust/cargo-bitbake/pull/21 fixes it.

**Comment by jluebbe** [comment]
I have the same error with stable 1.49.0 on Linux. To install it with `cargo install`, I had to use `--locked`, as cargo would build with a broken serde otherwise.
