### ISSUE TITLE
license

### ISSUE THREAD

**Issue by jwinarske** [meta-rust/cargo-bitbake#30]
How do I ensure license gets resolved?  In the case of a nested project would it make sense to pass in option for file name?  Something like 'cargo bitbake -l ../LICENSE'?

**Comment by weltling** [comment]
The project `Cargo.toml` is to contain `license = ` in the `package` section.

Thanks

**Comment by jwinarske** [comment]
Is that supposed to point to the file?  I was under the impression that was the license type.  For example:

    license = "Apache-2.0"

**Comment by jwinarske** [comment]
I see.  I need 'license-file = "../LICENSE"'
