### ISSUE TITLE
0.3.16 release due to new cargo

### ISSUE THREAD

**Issue by otavio** [meta-rust/cargo-bitbake#32]
The build fails with todays stable and nightly; I successfully built the tip today.

**Comment by jluebbe** [comment]
The fix was merged in https://github.com/meta-rust/cargo-bitbake/pull/27 and works fine for me.

**Comment by jluebbe** [comment]
@srwalter Can we reopen this, as no release was actually tagged or uploaded to crates.io?

**Comment by cardoe** [comment]
Unfortunately I'm not able to produce a release because its failing to build for me currently on my dev box.

```
  = note: ld: reference to symbol (which has not been assigned an address) __ZN4
curl4init9INIT_CTOR17h52e5a6ce1731886eE in '__ZN4curl4init17h4b2fd770f1576c88E' from /Users/cardoe/work/cargo-bitbake/target/package/cargo-bitbake-0.3.16-alpha.
0/target/debug/deps/libcurl-e5052614d62e5d75.rlib(curl-e5052614d62e5d75.curl.f364c615-cgu.15.rcgu.o) for architecture arm64
          clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by cph-w** [comment]
I am using the legacy overrides feature on master, so I would love a release to avoid having to install from git and have a deterministic cargo-bitbake version for generated recipes.

If there are any issues blocking release I will be happy to contribute more to this wonderful tool if I can.

**Comment by jluebbe** [comment]
@cardoe Is there anything we can do to help (access to amd64 build VMs, ...)?

**Comment by otavio** [comment]
@kraj can you create a release?

**Comment by pmembrey** [comment]
@kraj any chance of a cargo release? I'm happy to help if I can ☺️

**Comment by jhartzell42** [comment]
@kraj I see the release but it's not on crates.io yet, has it just not been uploaded?

**Comment by cardoe** [comment]
The Rust issue on the M1 is taken care of and I've made the release.
