### ISSUE TITLE
Feature request: Provide mode to put exact git hash in bitbake recipe

### ISSUE THREAD

**Issue by jhartzell42** [meta-rust/cargo-bitbake#33]
Similar to a cargo.lock file containing the exact revision of a git repo, I want my bitbake recipes, especially when covering internal deps, to do the same. I don't think this should necessary be the default behavior, but I think it should be an option.

 I have posted a pull request to accomplish this.

**Comment by jhartzell42** [comment]
@kraj do you think this should be the default behavior, or the previous default? I'm now wondering why the decision was made to go with branch names over specific commits when generating the `bb` file in the first place, as a colleague of mine pointed out to me that reproducibility was one of the goals of Yocto.

**Comment by kraj** [comment]
we need both branch name and commit SHA for best results.
