### ISSUE TITLE
Unable to install on Ubuntu 22.04

### ISSUE THREAD

**Issue by Ecordonnier** [meta-rust/cargo-bitbake#54]
I tried to install cargo-bitbake on Ubuntu 22.04, with locked version and without the locked parameter (see the errors in the log files: the "not locked" version causes "error[E0283]: type annotations needed" and the locked version causes "error: failed to run custom build command for `openssl-sys v0.9.54`"). Note that libssl-dev and pkg-config are installed on the system. Is it a known issue?

[packages.txt](https://github.com/meta-rust/cargo-bitbake/files/8969104/packages.txt)
[cargo-bitbake-locked.txt](https://github.com/meta-rust/cargo-bitbake/files/8969105/cargo-bitbake-locked.txt)
[cargo-bitbake-not-locked.txt](https://github.com/meta-rust/cargo-bitbake/files/8969106/cargo-bitbake-not-locked.txt)

**Comment by Ecordonnier** [comment]
I solved the issue by using another version of cargo:

- The compilation with cargo version 1.24.3 from the snap package "rustup" of Ubuntu 22.04 is not working.
- The compilation with cargo version 0.60.0 from the apt package "cargo" of Ubuntu 22.04 is not working
- The compilation with cargo version 1.62.0 (downloaded with `curl https://sh.rustup.rs -sSf | sh`) is working.

**Comment by etienne-cor** [comment]
This is caused by https://github.com/rust-lang/cargo/issues/10623
